const { Router } = require('express');
const { authMiddleware } = require('../middleware/auth');
const { requireRole } = require('../middleware/roles');
const { getEstaciones, getEstacionById, getAccesosByEstacion, alertaCapacidad, crearEstacion, actualizarEstacion } = require('../controllers/estaciones.controller');
const router = Router();
router.get('/',                      authMiddleware, getEstaciones);
router.get('/:id',                   authMiddleware, getEstacionById);
router.get('/:id/accesos',           authMiddleware, getAccesosByEstacion);
router.post('/',                     authMiddleware, requireRole('admin', 'supervisor'), crearEstacion);
router.put('/:id',                   authMiddleware, requireRole('admin', 'supervisor'), actualizarEstacion);
router.post('/:id/alerta-capacidad', authMiddleware, alertaCapacidad);
module.exports = router;
