const { Router } = require('express');
const { authMiddleware } = require('../middleware/auth');
const { requireRole } = require('../middleware/roles');
const { getPilotos, getPilotoById, createPiloto, updatePiloto } = require('../controllers/pilotos.controller');
const router = Router();
router.get('/',    authMiddleware, requireRole('admin', 'supervisor'), getPilotos);
router.get('/:id', authMiddleware, requireRole('admin', 'supervisor'), getPilotoById);
router.post('/',   authMiddleware, requireRole('admin', 'supervisor'), createPiloto);
router.put('/:id', authMiddleware, requireRole('admin', 'supervisor'), updatePiloto);
module.exports = router;
